### ISSUE TITLE
Error after :LiveMark command

### ISSUE THREAD

**Issue by arings** [miyakogi/livemark.vim#4]
neovim v0.2.1-dev
```
Error detected while processing function livemark#enable_livemark[13]..<SNR>50_start_server:
line   34:                                                                                  
Failed to start livemark server: b'Traceback (most recent call last):\n  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as
_main\n    "__main__", mod_spec)\n  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/hom
e/mk-61/.vim/plugged/livemark.vim/plugin/livemark/livemark/__main__.py", line 43, in <module>\n    from wdom.tag import Div, Style, H2, 
Script, WdomElement  # noqa: E402\n  File "/home/mk-61/.vim/plugged/livemark.vim/plugin/livemark/wdom/wdom/tag.py", line 11, in <module>
\n    from wdom.element import _AttrValueType\n  File "/home/mk-61/.vim/plugged/livemark.vim/plugin/livemark/wdom/wdom/element.py", line
 26, in <module>\n    class DOMTokenList(MutableSequence[str]):\n  File "/home/mk-61/.vim/plugged/livemark.vim/plugin/livemark/wdom/wdom
/element.py", line 32, in DOMTokenList\n    def __init__(self, owner: Union[Node, Type[\'HTMLElement\']],\n  File "/usr/lib/python3.5/ty
ping.py", line 552, in __getitem__\n    dict(self.__dict__), parameters, _root=True)\n  File "/usr/lib/python3.5/typing.py", line 512, i
n __new__\n    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):\n  File "/usr/lib/python3.5/typing.py", line 512, in <genexp
r>\n    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):\n  File "/usr/lib/python3.5/typing.py", line 1077, in __subclassche
ck__\n    if super().__subclasscheck__(cls):\n  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__\n    for scls in cls.__
subclasses__():\nTypeError: descriptor \'__subclasses__\' of \'type\' object needs an argument\n'^@
```

vim 8:
```
Error detected while processing function livemark#enable_livemark[1]..<SNR>47_check_features:
line    3:
Livemark.vim requires vim which supports "channel" or "python".
```

vim features:
```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep  4 2017 11:02:18)
Included patches: 1-1052
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +conceal         +file_in_path    +libcall         +mouse_sgr       +profile         +tag_old_static  +visualextra
+arabic          +cryptv          +find_in_path    +linebreak       -mouse_sysmouse  -python          -tag_any_white   +viminfo
+autocmd         +cscope          +float           +lispindent      +mouse_urxvt     +python3         +tcl             +vreplace
+balloon_eval    +cursorbind      +folding         +listcmds        +mouse_xterm     +quickfix        +termguicolors   +wildignore
+browse          +cursorshape     -footer          +localmap        +multi_byte      +reltime         +terminal        +wildmenu
++builtin_terms  +dialog_con_gui  +fork()          +lua             +multi_lang      +rightleft       +terminfo        +windows
+byte_offset     +diff            +gettext         +menu            -mzscheme        +ruby            +termresponse    +writebackup
+channel         +digraphs        -hangul_input    +mksession       +netbeans_intg   +scrollbind      +textobjects     +X11
+cindent         +dnd             +iconv           +modify_fname    +num64           +signs           +timers          -xfontset
+clientserver    -ebcdic          +insert_expand   +mouse           +packages        +smartindent     +title           +xim
+clipboard       +emacs_tags      +job             +mouseshape      +path_extra      +startuptime     +toolbar         +xpm
+cmdline_compl   +eval            +jumplist        +mouse_dec       +perl            +statusline      +user_commands   +xsmp_interact
+cmdline_hist    +ex_extra        +keymap          +mouse_gpm       +persistent_undo -sun_workshop    +vertsplit       +xterm_clipboard
+cmdline_info    +extra_search    +lambda          -mouse_jsbterm   +postscript      +syntax          +virtualedit     -xterm_save
+comments        +farsi           +langmap         +mouse_netterm   +printer         +tag_binary      +visual
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/in
clude/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0
/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/
harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/in
clude/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/includ
e -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbol
ic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-
gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -
lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/pe
rl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm
 -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm

```

**Comment by miyakogi** [comment]
Sorry, neovim is not supported and this plugin is no longer maintained.
[miyakogi/vim-livemark2](https://github.com/miyakogi/vim-livemark2) is successor of this but under development.
It also does not support neovim, but may work.
